### ISSUE TITLE
user mannual not generated

### ISSUE THREAD

**Issue by airobert** [stonneau/hpp-rbprm#3]
Dear Steve,

I can't find the user mannual at $DEVEL_DIR/install/share/doc/hpp-rbprm/doxygen-html/index.html
What should I do?
Thanks!

**Comment by anna-seppala** [comment]
Calling "make install" in the build folder of the package generates the documentation in the correct folder.

**Comment by airobert** [comment]
Sorry I thought I have called "make install". The issue has been resolved.
Thanks all the same!

On 6 June 2016 at 11:04, anna-seppala notifications@github.com wrote:

> Calling "make install" in the build folder of the package generates the
> documentation in the correct folder.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/stonneau/hpp-rbprm/issues/3#issuecomment-223904856,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACaalXveNtZqw5YZIdgRklLI-RvT9d49ks5qI-KEgaJpZM4Iur7J
> .

## 

Cordialement/Regards,
Robert (Shuai Wang) @ LAAS-CNRS
https://airobert.github.io/
